### ISSUE TITLE
Can't login to the account using snap built-in browser using Google

### ISSUE THREAD

**Issue by haddagart** [Pietrucci-Blacher/notion-snap-reborn#92] opened 2023-12-14 20:01 UTC
I can't login to my Notion account using Google authentification. The snap built-in browser is saying that either the browser or the app is not secure. Is it possible to make the authentification out of the scope of built-in browser and use a user defined one (like Google Chrome it is working fine for me).

**Issue reported on:**
- OS: Kubuntu 22.04.3 LTS x86_64
- Kernel: 6.2.0-39-generic 
- Packages: 3581 (dpkg), 22 (snap)

**Here's a screenshot of the error/problem**
![2023-12-14_20-57](https://github.com/Pietrucci-Blacher/notion-snap-reborn/assets/22382156/c7c61396-1106-48ab-9029-1bbadaf8e8a9)

**Comment by nicolas-farrie** [comment] 2023-12-20 17:02
Same problem.
I got the pb this week using the notion-snap app. I tried to remove it and install this notion-snap-reborn app.
Pb still the same with the two apps !
May be it could help

PS: launching from console, get an graphic gtk warning - in case it have a role .. :+1: 
`(notion-snap-reborn:66547): Gtk-WARNING **: 17:26:54.163: Theme parsing error: gtk-dark.css:3748:23: 'font-feature-settings' is not a valid property name
Warning: vkCreateInstance: Found no drivers!
Warning: vkCreateInstance failed with VK_ERROR_INCOMPATIBLE_DRIVER
    at CheckVkSuccessImpl (../../third_party/dawn/src/dawn/native/vulkan/VulkanError.cpp:101)
    at CreateVkInstance (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:493)
    at Initialize (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:379)
    at Create (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:301)
    at operator() (../../third_party/dawn/src/dawn/native/vulkan/BackendVk.cpp:556)
`

**Comment by Pietrucci-Blacher** [comment] 2023-12-29 13:30
Hi, I'm currently working on it, the problem is simply that Google has strengthened its security measures with regard to supported browsers (this no longer includes Electron). So I'll probably release a major notion-snap-reborn update for the next version :ok_hand:

**Comment by trex827** [comment] 2024-02-01 13:10
I'm having the same problem on Fedora 39 KDE spin.  Any progress on this issue?

Login screen will take only the first character and then notion locks up.  


Operating System: Fedora Linux 39
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.113.0
Qt Version: 5.15.12
Kernel Version: 6.6.13-200.fc39.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Pentium® CPU 6405U @ 2.40GHz
Memory: 3.6 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics
Manufacturer: LENOVO
Product Name: 81WA
System Version: IdeaPad 3 14IML05

**Comment by Pietrucci-Blacher** [comment] 2024-02-01 13:29
Hi, I'm currently quite busy but it's progressing well and at the same time I'm working on another way to support more software architectures because currently notion-snap-reborn only supports AMD64. 👌

**Comment by KestiNet** [comment] 2024-02-22 00:02
Im also having this issue on Ubuntu 23.10 Linux 6.5.0-17-generic

**Comment by hellbound22** [comment] 2024-02-27 21:07
Same issue on Ubuntu 22.03. While this is not resolved, is there a workaround?

**Comment by Shaco74** [comment] 2024-03-01 08:48
Same issue here, i am runnning Kubuntu: Ubuntu 23.10

**Comment by franklegolasyoung** [comment] 2024-03-07 02:06
same issue on Ubuntu 22.04

**Comment by ulvimemmeedov** [comment] 2024-03-14 16:17
I have a solution for this problem please check #131

**Comment by Pietrucci-Blacher** [comment] 2024-03-14 18:27
@ulvimemmeedov, hi dude, wow thanks, I'm going to test it right now and I'll let you know if it works on my side. Thank you very much for your suggestion because it's one of the subjects that was bothering me enormously, hence my preparation for V2 ;)

**Comment by Pietrucci-Blacher** [comment] 2024-03-14 19:02
Fixed in #132, again a big shout-out and thanks to @ulvimemmeedov

**Closed by Pietrucci-Blacher** 2024-03-14 19:02 UTC
Labels: bug, help wanted, good first issue, Work in progress

**Comment by Shaco74** [comment] 2024-03-15 12:32
Nice work! 
Works on Kubuntu: Ubuntu 23.10
